### PR TITLE
feat: Added a helper function to print multiple tables at once.

### LINKED ISSUE #375: Feature request: print multiple tables, side-by-side
Thanks for this library. I really appreciate how easy it was to quickly understand and apply. Nice job on the docs and API design!

I found myself printing a couple narrow tables, where they could have fit side-by-side in my terminal. Something like this:

```
       Table One               Table Two 
┌───────┬──────┬──────┐ ┌───────┬──────┬──────┐
│ Foo   │ Bar  │ Baz  │ │ Foo   │ Bar  │ Baz  │
├───────┼──────┼──────┤ ├───────┼──────┼──────┤
│ aaa   │   13 │    8 │ │ aaa   │   43 │    8 │
│ bbb   │   99 │   10 │ │ bbb   │   12 │   10 │
│ ccc   │   91 │    9 │ │ ccc   │   12 │    9 │
│ ddd   │   45 │    6 │ │ ddd   │   75 │    6 │
│ eee   │   32 │    4 │ │ eee   │   62 │    4 │
│ fff   │   31 │    4 │ │ fff   │   61 │    4 │
│ ggg   │   26 │    3 │ │ ggg   │   56 │    3 │
│ hhh   │   12 │    7 │ └───────┴──────┴──────┘
│ iii   │   21 │    7 │ 
└───────┴──────┴──────┘ 
```

Would you be open to a PR that adds something like this? I'm thinking the API could be something like:
```ts
import { printTables } from "console-table-printer";
// ...
printTables(table1,table2);
```

### PR DESCRIPTION
**Pull request by ArjixWasTaken**
## 👀What is this pr about?

This PR aims to add a function that will print multiple tables at once.
If the size of the terminal cannot fit them side by side, it will print as many as it can at once
And print the others below, side by side.

### Added

- [x] printTables

### Fixed
#375 

| Before | After |
| ------ | ----- |
|  🧟    | 😎    |

### CODE REVIEW

**Comment by ArjixWasTaken** [comment]
The function can be imported like this:
```js
import { printTables } from "console-table-printer/utils/table-helpers"
```

And you can pass any number of tables into it in order to print them.

**Comment by ArjixWasTaken** [comment]
PS:
```
I didn't test this package wide.
I only tested the function directly.
So please check for me because I'm super lazy.
```

**Comment by ArjixWasTaken** [comment]
For some reason this took way more effort than what it's worth.

**Comment by ayonious** [comment]
as mentioned in https://github.com/ayonious/console-table-printer/issues/375 this does not seem like a feature that many would use. 

But also looking at code its little difficult to understand. Im okay to put the simpler version without considering the width. That way at least the most common cases will be handled.

**Comment by ArjixWasTaken** [comment]
If the code is difficult to understand then I can explain it (or even refactor when I'm back from my trip)

It basically tries to merge as many tables as possible, if the character limit is reached it then prints them below.

Think of it like a buffer, you save data up to the buffer size and then flush the buffer.

That's what I do, I make a "buffer" that gets flushed when the end is reached or the maximum character limit gets hit.

**Comment by ayonious** [comment]
@ArjixWasTaken thanks for putting time into this.

But to make it maintainable, more things needs to be changed:

- There could be more variable naming, new functions creating, unit tests creating done on this one. 
- Also maybe its better to expose the function to be directly accessible instead of this utils file.

**Comment by ayonious** [comment]
@ArjixWasTaken thanks for putting time into this.

But to make it maintainable, more things needs to be changed:

- There could be more variable naming, new functions creating, unit tests creating done on this one. 
- Also maybe its better to expose the function to be directly accessible instead of this utils file.

**Comment by ArjixWasTaken** [comment]
oof, pull bot made my PR empty...

**Comment by ArjixWasTaken** [comment]
thankfully a version of the code is available [here](https://github.com/ayonious/console-table-printer/issues/375)

**Pull request merged**
